import { Inter } from "next/font/google";
// import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "../component/header";
import Footer from "../component/footer";
import Sidebar from "../component/sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="content d-flex flex-column min-vh-100">
          <Header />

          <div className="flex-grow-1 ">{children}</div>

          <Footer />
        </main>
      </body>
    </html>
  );
}
